[toolchain]
anchor_version = "0.29.0"
solana_version = "1.18.17"

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_test = "89m59ppH36q9YUJYzwKGRWLGePtYU5wbHt8mKq3VKhHg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/patrick/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
